export const reset = '\x1b[0m'
export const Bright = '\x1b[1m'
export const dim = '\x1b[2m'
export const Underscore = '\x1b[4m'
export const Blink = '\x1b[5m'
export const Reverse = '\x1b[7m'
export const Hidden = '\x1b[8m'

export const ForegroundBlack = '\x1b[30m'
export const ForegroundRed = '\x1b[31m'
export const ForegroundGreen = '\x1b[32m'
export const ForegroundYellow = '\x1b[33m'
export const ForegroundBlue = '\x1b[34m'
export const ForegroundMagenta = '\x1b[35m'
export const ForegroundCyan = '\x1b[36m'
export const ForegroundWhite = '\x1b[37m'
export const BackgroundBlack = '\x1b[40m'

export const BackgroundRed = '\x1b[41m'
export const BackgroundGreen = '\x1b[42m'
export const BackgroundYellow = '\x1b[43m'
export const BackgroundBlue = '\x1b[44m'
export const BackgroundMagenta = '\x1b[45m'
export const BackgroundCyan = '\x1b[46m'
export const BackgroundWhite = '\x1b[47m'
