export {
  NumberLiteralType,
  StringLiteralType,
  BooleanLiteralType,
  TypeRetriever,
  Type,
  PrimitiveType,
  Parameter,
  FunctionType,
  ClassMember,
  AccessModifier,
  Property,
  Method,
  Decorator,
  ConstructSignature,
  ClassType,
  ClassLocation,
  InterfaceType,
  ObjectType,
  GenericInstance,
  AliasType,
  UnionType,
  IntersectionType,
  TupleType,
  TypeParameter,
  UnsupportedType,
  ESModule,
  ArrayType,
  MapType,
  PromiseType,
  SetType,
  CallSignature,
  ExternalType,
  Statics,
  Int8ArrayType,
  BuiltInType,
  GenericBuiltIn,
  EnumType,
  IndexSignature,
} from './lib/types'

export {
  isType,
  isPrimitiveType,
  isNumberType,
  isStringType,
  isBooleanType,
  isBigIntType,
  isUnsupportedType,
  isTupleType,
  isObjectType,
  isUnionType,
  isIntersectionType,
  isAliasType,
  isClassType,
  isFunctionType,
  isInterfaceType,
  isVariableDeclaration,
  isSetType,
  isArrayType,
  isGenericBuiltIn,
  isMapType,
  isModuleType,
  isPromiseType,
  isEnumType,
  isGenericInstance,
  isReferableType,
  isObjectLike,
  assertNumberType,
  assertStringType,
  assertBooleanType,
  assertBigIntType,
  assertClassType,
  assertObjectType,
  assertInterfaceType,
  assertGenericInstance,
  assertAliasType,
  assertUnionType,
  assertIntersectionType,
  assertFunctionType,
  assertTupleType,
  assertUnsupportedType,
  assertPromiseType,
  assertMapType,
  assertArrayType,
  assertGenericBuiltIn,
  assertSetType,
  assertEnumType,
  assertReferableType,
  assertPrimitiveType,
  assertModuleType,
  assertType,
  assertVariableDeclaration,
  TypeAssertionError,
  ReferableType,
} from './lib/types/guards'

export { TypeStore } from './lib/TypeStore'

export { typeOf } from './lib/typeOf'
export { ObjectLike } from './lib/types/ObjectLike'
